# Generated by Django 3.2.3 on 2021-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_info',
            name='subject',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
