# Generated by Django 3.2.3 on 2021-06-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_userprofile_usrename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(default='', upload_to='profile_photos/'),
        ),
    ]
