# Generated by Django 3.2.3 on 2021-06-10 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_time', models.TimeField(auto_now=True)),
                ('post_date', models.DateField(auto_now=True)),
                ('post_image', models.ImageField(default='', upload_to='post_image/')),
                ('post_content', models.TextField(max_length=500)),
                ('post_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
