# Generated by Django 3.2.3 on 2021-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210616_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_status',
            field=models.BooleanField(default=False),
        ),
    ]
