# Generated by Django 3.2.3 on 2021-07-06 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField(default=0)),
                ('product_photo', models.ImageField(default=None, upload_to='product_photo')),
                ('product_time_added', models.TimeField(auto_now=True)),
                ('product_date_added', models.DateField(auto_now=True)),
                ('transaction_code', models.CharField(max_length=10)),
                ('product_aviability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=17)),
                ('product_condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=20)),
                ('product_description', models.CharField(default='', max_length=150)),
                ('product_quantity', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='')),
                ('add_to_cart', models.ManyToManyField(blank=True, null=True, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('add_to_compare', models.ManyToManyField(blank=True, null=True, related_name='compare', to=settings.AUTH_USER_MODEL)),
                ('add_to_wishlist', models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='main.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='main_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.IntegerField(default=0)),
                ('e_mail', models.EmailField(max_length=30)),
                ('facebook_link', models.CharField(max_length=50)),
                ('twitter_link', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=50)),
                ('google_link', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(default=0, max_length=50)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='Profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField()),
                ('review_time', models.TimeField(auto_now=True)),
                ('review_date', models.DateField(auto_now=True)),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_time_added', models.TimeField(auto_now_add=True)),
                ('item_date_added', models.DateField(auto_now_add=True)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='main.index')),
                ('item_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
