# Generated by Django 3.2.3 on 2021-06-07 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField(default=0)),
                ('add_to_cart', models.ManyToManyField(related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('add_to_compare', models.ManyToManyField(related_name='compare', to=settings.AUTH_USER_MODEL)),
                ('add_to_wishlist', models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
