# Generated by Django 3.2.3 on 2021-06-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.index')),
            ],
        ),
    ]
