# Generated by Django 3.2.3 on 2021-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
