# Generated by Django 3.2.3 on 2021-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_footer',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='e_mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='facebook_link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='google_link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='linkedin_link',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='twitter_link',
            field=models.CharField(max_length=30),
        ),
    ]
