# Generated by Django 3.2.3 on 2021-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210610_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_footer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='facebook_link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='google_link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='linkedin_link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main_footer',
            name='twitter_link',
            field=models.CharField(max_length=50),
        ),
    ]
