# Generated by Django 3.2.3 on 2021-06-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210610_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='main.index')),
            ],
        ),
    ]
