# Generated by Django 3.2.3 on 2021-07-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210728_1715'),
        ('main', '0005_country_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.CreateModel(
            name='shippinginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('shipping_middlename', models.CharField(default='', max_length=50)),
                ('shipping_adress1', models.CharField(max_length=500)),
                ('shipping_adress2', models.CharField(default='', max_length=50)),
                ('shipping_zipcode', models.CharField(max_length=10)),
                ('shipping_phone', models.CharField(max_length=50)),
                ('shipping_mobile_number', models.CharField(max_length=50)),
                ('shipping_fax', models.CharField(max_length=50)),
                ('shipping_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_country', to='main.country')),
                ('shipping_firstname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_firstname', to='Profile.userprofile', to_field='firstname')),
                ('shipping_lastname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile', to_field='lastname')),
                ('shipping_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_mail', to='Profile.userprofile', to_field='email')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_order', to='main.order')),
                ('shipping_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_state', to='main.state')),
                ('shipping_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_user', to='Profile.userprofile')),
            ],
        ),
    ]
