# Generated by Django 3.2.3 on 2021-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='product_photo',
            field=models.ImageField(default='', upload_to='product_photo'),
        ),
    ]
