# Generated by Django 3.2.3 on 2021-06-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210623_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_category',
        ),
        migrations.AddField(
            model_name='index',
            name='product_brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='main.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category'),
            preserve_default=False,
        ),
    ]
