# Generated by Django 3.2.3 on 2021-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210623_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='index',
            name='product_date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='index',
            name='product_time_added',
            field=models.TimeField(auto_now=True),
        ),
    ]
