# Generated by Django 3.2.3 on 2021-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210625_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
