# Generated by Django 3.2.3 on 2021-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_index_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='transaction_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
