# Generated by Django 3.2.3 on 2021-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_index_product_aviability'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='product_condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=20),
        ),
    ]
