# Generated by Django 3.2.3 on 2021-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_index_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='product_description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
